load("@bazel_lib//:bzl_library.bzl", "bzl_library")

exports_files(
    glob(["*.bzl"]),
    visibility = ["//docs:__pkg__"],
)

bzl_library(
    name = "binary",
    srcs = ["binary.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "//d/private/rules:compile",
        "//d/private/rules:link",
        "@bazel_lib//lib:expand_make_vars",
    ],
)

bzl_library(
    name = "cc_toolchain",
    srcs = ["cc_toolchain.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "@rules_cc//cc:action_names_bzl",
        "@rules_cc//cc:find_cc_toolchain_bzl",
        "@rules_cc//cc/common",
    ],
)

bzl_library(
    name = "bitcode",
    srcs = ["bitcode.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "//d/private/rules:utils",
    ],
)

bzl_library(
    name = "compile",
    srcs = ["compile.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "//d:providers",
        "//d/private:providers",
        "//d/private/rules:bitcode",
        "//d/private/rules:source_map",
        "//d/private/rules:utils",
        "@bazel_skylib//lib:dicts",
        "@bazel_skylib//lib:paths",
    ],
)

bzl_library(
    name = "library",
    srcs = ["library.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "//d/private/rules:compile",
    ],
)

bzl_library(
    name = "link",
    srcs = ["link.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "//d/private/rules:cc_toolchain",
        "@rules_cc//cc:defs_bzl",
    ],
)

bzl_library(
    name = "test",
    srcs = ["test.bzl"],
    visibility = [
        "//d:__subpackages__",
        "//docs:__subpackages__",
    ],
    deps = [
        "//d/private/rules:compile",
        "//d/private/rules:link",
        "@bazel_lib//lib:expand_make_vars",
        "@rules_cc//cc:find_cc_toolchain_bzl",
    ],
)

bzl_library(
    name = "utils",
    srcs = ["utils.bzl"],
    visibility = ["//d:__subpackages__"],
)

bzl_library(
    name = "source_map",
    srcs = ["source_map.bzl"],
    visibility = ["//d:__subpackages__"],
)