package(default_visibility = ["//visibility:public"])

constraint_setting(
    name = "d_compiler",
    default_constraint_value = ":dmd",
)

constraint_value(
    name = "dmd",
    constraint_setting = ":d_compiler",
)

constraint_value(
    name = "ldc",
    constraint_setting = ":d_compiler",
)

