load("//d:cycles.bzl", "d_library")
load("//d:defs.bzl", "d_test")

d_library(
    name = "a",
    srcs = ["a.d"],
    deps = [
        # We need to depend on b here, but bazel doesn't allow cycles, so we use a cycle breaker target instead
        ":b-cycle-breaker",
    ],
)

d_library(
    name = "b",
    srcs = ["b.d"],
    deps = [":a"],
)

d_test(
    name = "cyclic_deps_test",
    args = [
        "--DRT-oncycle=ignore",
    ],
    srcs = ["cyclic_deps_test.d"],
    linker_script = "linker_script.lld.t",
    deps = [
        ":a",
        ":b",
    ],
)